### ISSUE TITLE
Error: "Operator is only a shell"

### ISSUE THREAD

**Issue by bbarany** [credativ/db2fce#4]
The extension is installed in a default way in schema db2.

db2 is on the search_path.

Using the ^= (not equal) operator results only in the error message "Operator is only a shell" (Operator ist nur eine Hülle).

It was tried with timestamp without time zone and integer values.

**Comment by mbanck** [comment]
I get this to work if I explicitly add ```pg_catalog``` to the search path:

```
postgres=# SET search_path = db2fce, "$user", public;
SET
postgres=# SELECT '2017-06-30 09:39:10.911531+02' ^= '2017-06-30 09:39:10.911531+03';
FEHLER:  Operator ist nur eine Hülle: text ^= text
LINE 1: SELECT '2017-06-30 09:39:10.911531+02' ^= '2017-06-30 09:39:...
                                               ^
postgres=# SET search_path = db2,pg_catalog,public;
SET
postgres=# SELECT '2017-06-30 09:39:10.911531+02' ^= '2017-06-30 09:39:10.911531+03';
 ?column? 
----------
 t
(1 row)
```

I'll see whether this can be dealt with in the extension.

**Comment by mbanck** [comment]
```
> postgres=# SET search_path = db2fce, "$user", public;
```

That was stupid, the schema name is ```db2``` not ```db2fce```. So with that, it actually works for me:

```
postgres=# SET search_path = db2, "$user", public;
SET
postgres=# SELECT '2017-06-30 09:39:10.911531+02' ^= '2017-06-30 09:39:10.911531+03';
 ?column? 
----------
 t
(1 row)
```

Are you sure your ```search_path``` is correct?

**Comment by bbarany** [comment]
Thanks, adding the pg_catalog fixed it. 

It seems to be a problem when pg_catalog is searched before db2. I'll update the database settings.

**Comment by bbarany** [comment]
Closing solved issue.

**Comment by mbanck** [comment]
I've now changed it so that `search_path` is explicitly set to `db2` when the objects are created. This way, the operator shells should no longer end up in `pg_catalog` or wherever.
